**Numpy**
- Numpy is a numerical computing library for python.
- Numpy support multi dimensional arrays and matrices
- It has a lot of in-built mathematical functions

**Why Numpy ?**
- performs fast operations (because of Vectorization)
- numpy arrays can be treated as vectors and matrices from linear algebra

In [1]:
# Installing numpy library 
!pip install numpy

In [2]:
# Importing numpy as np 
import numpy as np 

In [3]:
# It take 287 nano seconds for calculation 
lst = [1,2,3,4,5,6,7,8,9,10]
%timeit square_lst = [i**2 for i in lst]
print("New Square List:",square_lst)

289 ns ± 2.46 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


NameError: name 'square_lst' is not defined

In [ ]:
# Finding calculation time of calulating square of list using array
lst_array = np.array(lst)
lst_array
%timeit square_array = lst_array ** 2
print("New Square Array:", square_array)
# Using array it takes 229 nano sceonds for calculation it means array is faster than list 

In [ ]:
# if we want add 1 to each elements in list it doesnot allow. 
new_list = lst + 1

In [ ]:
# if we want add 1 to each elements in arrayt it allow. 
new_array = lst_array + 1
print("Added 1 array:", new_array)


**Numpy Basics**
array: Fundamental element in numpy is homogenous array. Numpy Arrays can be 1D, 2D, 3D... nD
- Different ways to create np array
1. np.array ( )
2. np.arange ()
3. np.linspace()

**USING np.array()**

In [ ]:
list_ = [1,2,3,4,5,6,7,8,9]
list_array = np.array(list_)
list_array

In [ ]:
# Finding dimension of array
print("Dimension of above array is",list_array.ndim)

In [ ]:
# finding shape of array
print("Shape of above array is",list_array.shape)

In [ ]:
# finding size of array
print("Shape of above array is",list_array.size)

**USING np.arange()**

In [ ]:
new_array = np.arange(1,11)
new_array

In [ ]:
# Dimesion
new_array.ndim

In [ ]:
# shape
new_array.shape

In [ ]:
# size
new_array.size

**USING np.linspace()** (0,100,3) = (100/3-1)

In [ ]:
new_array1 = np.linspace(0,100,3)
new_array1

In [ ]:
# Creating two dimensional array 
twoD_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
twoD_array

In [ ]:
# Finding dimension of array
twoD_array.ndim

In [ ]:
# finding shape of array
twoD_array.shape

In [ ]:
# finding size of array
twoD_array.size

In [4]:
# Creating zeros array
zero_array = np.zeros((4,2), dtype=int)
zero_array

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [5]:
# Creating one array
ones_array = np.ones((3,4), dtype=int)
ones_array

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [6]:
# Creating empty array
empty_array = np.empty((3,2), dtype= int)
empty_array

array([[0, 0],
       [0, 0],
       [0, 0]])

In [7]:
# Creating random array
random_array = np.random.rand(3)
random_array

array([0.9537641 , 0.24439927, 0.45959735])

**INDEXING**

In [9]:
array = np.random.randint(1,100,(5,4))
array

array([[45, 89, 89, 67],
       [74, 22, 78, 43],
       [77, 52, 42,  1],
       [55, 13, 32, 79],
       [46, 60, 85, 60]])

In [11]:
# First row 
array[0]

array([45, 89, 89, 67])

In [13]:
# second last row 
array[-2]

array([55, 13, 32, 79])

In [18]:
# first element
print("First Element:",array[0,0])

# last element
print("Last Element:",array[-1,-1])

First Element: 45
Last Element: 60


**SLICING**
1. arrl start_ row_idx : end row idx + 1, start_col _idx : end _col _idx+1]

In [19]:
new_array = array
new_array

array([[45, 89, 89, 67],
       [74, 22, 78, 43],
       [77, 52, 42,  1],
       [55, 13, 32, 79],
       [46, 60, 85, 60]])

In [24]:
# 3rd row to last row and 4th column to 5th column 
new_array[2:5, 2:5]

array([[42,  1],
       [32, 79],
       [85, 60]])

In [33]:
# 3rd row to last row and 1st column to last column 
new_array[2: , 0:]

array([[77, 52, 42,  1],
       [55, 13, 32, 79],
       [46, 60, 85, 60]])

In [30]:
# third column only 
new_array[ :,2]

array([89, 78, 42, 32, 85])

In [32]:
# upto third row
new_array[:3]

array([[45, 89, 89, 67],
       [74, 22, 78, 43],
       [77, 52, 42,  1]])

In [37]:
# changing element value 
new_array[0,0] = 46
new_array

array([[46, 89, 89, 67],
       [74, 22, 78, 43],
       [77, 52, 42,  1],
       [55, 13, 32, 79],
       [46, 60, 85, 60]])

In [41]:
# Total elements
new_array.size

20

In [38]:
# Masking 
mask = new_array > 50
print(mask)

[[False  True  True  True]
 [ True False  True False]
 [ True  True False False]
 [ True False False  True]
 [False  True  True  True]]


In [40]:
# Elements that are greater than 50
np.sum(mask)

12

In [43]:
# listing elemts that are greater than 50
new_array[mask]

array([89, 89, 67, 74, 78, 77, 52, 55, 79, 60, 85, 60])

**Operations in numpy array**

In [57]:
a = np.arange(1,10)
b = np.arange(10,19)


In [58]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [60]:
# sum
sum_array = a + b
sum_array

array([11, 13, 15, 17, 19, 21, 23, 25, 27])

In [61]:
# difference 
sub_array = b - a
sub_array

array([9, 9, 9, 9, 9, 9, 9, 9, 9])

In [62]:
# multiply
mult_array = a * b
mult_array

array([ 10,  22,  36,  52,  70,  90, 112, 136, 162])

In [63]:
# square of a each elements 
sq_array = a**2
print(sq_array)

[ 1  4  9 16 25 36 49 64 81]


In [66]:
# Now operation on (3*3) matrices
new_a = a.reshape(3,3)
new_b = b.reshape(3,3)

In [67]:
new_a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
new_b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [70]:
# operation
sum_ = new_a + new_b
sum_


array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [71]:
subtract_ = new_b - new_a
subtract_

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [72]:
multiply_ = new_a * new_b
multiply_

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [73]:
new_a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
new_b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [78]:
# masking in new_a matrix 
mask = new_a > 5
print(mask)

[[False False False]
 [False False  True]
 [ True  True  True]]


In [79]:
np.sum(mask)

4

In [80]:
np.log(new_a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [81]:
np.sin(new_a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

**Matrix Dot Product**

In [84]:
new_a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
new_b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [89]:
# How dot product works
'''
[ 1*10+2*13+3*16  1*11+2*14+3*17  1*12+2*15+3*18]
[ 4*10+5*13+6*16  4*11+5*14+6*17  4*12+5*15+6*18]
[ 7*10+8*13+9*16  7*11+8*14+9*17  7*12+8*15+9*18] 

columns of first matrix must match with rows of second matux to perform dot product.
result take number of rows from first matrix and columns from second matrix
'''

'\n[ 1*10+2*13+3*16  1*11+2*14+3*17  1*12+2*15+3*18]\n[ 4*10+5*13+6*16  4*11+5*14+6*17  4*12+5*15+6*18]\n[ 7*10+8*13+9*16  7*11+8*14+9*17  7*12+8*15+9*18] \n\ncolumns of first matrix must match with rows of second matux to perform dot product.\nresult take number of rows from first matrix and columns from second matrix\n'

In [90]:
product = np.dot(new_a, new_b)
print(product)

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


In [95]:
new_a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
# square root of new_a matrix
np.sqrt(new_a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [93]:
# sum
np.sum(new_a)

45

In [94]:
# maximum
np.max(new_a)

9

In [96]:
# minimum
np.min(new_a)

1

In [97]:
# mean
np.mean(new_a)

5.0

In [98]:
# standard deviation
np.std(new_a)

2.581988897471611

In [99]:
# sum all by column wise
np.sum(new_a, axis=0)

array([12, 15, 18])

In [100]:
# sum all by rows wise
np.sum(new_a, axis=1)

array([ 6, 15, 24])

In [102]:
# Mean by column wise
np.mean(new_a, axis=0)

array([4., 5., 6.])

In [103]:
# Mean by rows wise
np.mean(new_a, axis=1)

array([2., 5., 8.])