**Numpy**
- Numpy is a numerical computing library for python.
- Numpy support multi dimensional arrays and matrices
- It has a lot of in-built mathematical functions

**Why Numpy ?**
- performs fast operations (because of Vectorization)
- numpy arrays can be treated as vectors and matrices from linear algebra

In [3]:
# Installing numpy library 
!pip install numpy

In [4]:
# Importing numpy as np 
import numpy as np 

In [11]:
# It take 287 nano seconds for calculation 
lst = [1,2,3,4,5,6,7,8,9,10]
%timeit square_lst = [i**2 for i in lst]
print("New Square List:",square_lst)

287 ns ± 0.726 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
New Square List: [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [15]:
# Finding calculation time of calulating square of list using array
lst_array = np.array(lst)
lst_array
%timeit square_array = lst_array ** 2
print("New Square Array:", square_array)
# Using array it takes 229 nano sceonds for calculation it means array is faster than list 

229 ns ± 1.75 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
New Square Array: [  1   4   9  16  25  36  49  64  81 100]


In [16]:
# if we want add 1 to each elements in list it doesnot allow. 
new_list = lst + 1

TypeError: can only concatenate list (not "int") to list

In [18]:
# if we want add 1 to each elements in arrayt it allow. 
new_array = lst_array + 1
print("Added 1 array:", new_array)

Added 1 array: [ 2  3  4  5  6  7  8  9 10 11]



**Numpy Basics**
array: Fundamental element in numpy is homogenous array. Numpy Arrays can be 1D, 2D, 3D... nD
- Different ways to create np array
1. np.array ( )
2. np.arange ()
3. np.linspace()

**USING np.array()**

In [19]:
list_ = [1,2,3,4,5,6,7,8,9]
list_array = np.array(list_)
list_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# Finding dimension of array
print("Dimension of above array is",list_array.ndim)

Dimension of above array is 1


In [23]:
# finding shape of array
print("Shape of above array is",list_array.shape)

Shape of above array is (9,)


In [24]:
# finding size of array
print("Shape of above array is",list_array.size)

Shape of above array is 9


**USING np.arange()**

In [33]:
new_array = np.arange(1,11)
new_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
# Dimesion
new_array.ndim

1

In [35]:
# shape
new_array.shape

(10,)

In [36]:
# size
new_array.size

10

**USING np.linspace()** (0,100,3) = (100/3-1)

In [37]:
new_array1 = np.linspace(0,100,3)
new_array1

array([  0.,  50., 100.])

In [39]:
# Creating two dimensional array 
twoD_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
twoD_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
# Finding dimension of array
twoD_array.ndim

2

In [41]:
# finding shape of array
twoD_array.shape

(3, 3)

In [43]:
# finding size of array
twoD_array.size

9

In [63]:
# Creating zeros array
zero_array = np.zeros((4,2), dtype=int)
zero_array

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [64]:
# Creating one array
ones_array = np.ones((3,4), dtype=int)
ones_array

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [65]:
# Creating empty array
empty_array = np.empty((3,2), dtype= int)
empty_array

array([[0, 0],
       [0, 0],
       [0, 0]])

In [69]:
# Creating random array
random_array = np.random.rand(3)
random_array

array([0.78202864, 0.60026089, 0.74019111])