**Numpy**
- Numpy is a numerical computing library for python.
- Numpy support multi dimensional arrays and matrices
- It has a lot of in-built mathematical functions

**Why Numpy ?**
- performs fast operations (because of Vectorization)
- numpy arrays can be treated as vectors and matrices from linear algebra

In [6]:
# Installing numpy library 
!pip install numpy

In [15]:
# Importing numpy as np 
import numpy as np 

In [16]:
# It take 287 nano seconds for calculation 
lst = [1,2,3,4,5,6,7,8,9,10]
%timeit [i**2 for i in lst]


283 ns ± 2.22 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [20]:
# Finding calculation time of calulating square of list using array
lst_array = np.array(lst)
lst_array
%timeit lst_array ** 2
# Using array it takes 229 nano sceonds for calculation it means array is faster than list 

223 ns ± 1.55 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [22]:
# if we want add 1 to each elements in list it doesnot allow. 
new_list = lst + 1

TypeError: can only concatenate list (not "int") to list

In [23]:
# if we want add 1 to each elements in arrayt it allow. 
new_array = lst_array + 1
print("Added 1 array:", new_array)

Added 1 array: [ 2  3  4  5  6  7  8  9 10 11]



**Numpy Basics**
array: Fundamental element in numpy is homogenous array. Numpy Arrays can be 1D, 2D, 3D... nD
- Different ways to create np array
1. np.array ( )
2. np.arange ()
3. np.linspace()

**USING np.array()**

In [24]:
list_ = [1,2,3,4,5,6,7,8,9]
list_array = np.array(list_)
list_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# Finding dimension of array
print("Dimension of above array is",list_array.ndim)

Dimension of above array is 1


In [26]:
# finding shape of array
print("Shape of above array is",list_array.shape)

Shape of above array is (9,)


In [27]:
# finding size of array
print("Shape of above array is",list_array.size)

Shape of above array is 9


**USING np.arange()**

In [28]:
new_array = np.arange(1,11)
new_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# Dimesion
new_array.ndim

1

In [30]:
# shape
new_array.shape

(10,)

In [31]:
# size
new_array.size

10

**USING np.linspace()** (0,100,3) = (100/3-1)

In [32]:
new_array1 = np.linspace(0,100,3)
new_array1

array([  0.,  50., 100.])

In [33]:
# Creating two dimensional array 
twoD_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
twoD_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
# Finding dimension of array
twoD_array.ndim

2

In [35]:
# finding shape of array
twoD_array.shape

(3, 3)

In [36]:
# finding size of array
twoD_array.size

9

In [37]:
# Creating zeros array
zero_array = np.zeros((4,2), dtype=int)
zero_array

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [38]:
# Creating one array
ones_array = np.ones((3,4), dtype=int)
ones_array

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [39]:
# Creating empty array
empty_array = np.empty((3,2), dtype= int)
empty_array

array([[0, 0],
       [0, 0],
       [0, 0]])

In [40]:
# Creating random array
random_array = np.random.rand(3)
random_array

array([0.5315018 , 0.71418626, 0.47677888])

**INDEXING**

In [41]:
array = np.random.randint(1,100,(5,4))
array

array([[19, 25, 53, 71],
       [73,  6, 85, 15],
       [61, 66, 54, 75],
       [94,  6, 61, 23],
       [95, 61, 25, 92]])

In [42]:
# First row 
array[0]

array([19, 25, 53, 71])

In [43]:
# second last row 
array[-2]

array([94,  6, 61, 23])

In [44]:
# first element
print("First Element:",array[0,0])

# last element
print("Last Element:",array[-1,-1])

First Element: 19
Last Element: 92


**SLICING**
1. arrl start_ row_idx : end row idx + 1, start_col _idx : end _col _idx+1]

In [ ]:
new_array = array
new_array

In [ ]:
# 3rd row to last row and 4th column to 5th column 
new_array[2:5, 2:5]

In [ ]:
# 3rd row to last row and 1st column to last column 
new_array[2: , 0:]

In [ ]:
# third column only 
new_array[ :,2]

In [ ]:
# upto third row
new_array[:3]

In [ ]:
# changing element value 
new_array[0,0] = 46
new_array

In [10]:
# Total elements
new_array.size

NameError: name 'new_array' is not defined

In [11]:
# Masking 
mask = new_array > 50
print(mask)

NameError: name 'new_array' is not defined

In [12]:
# Elements that are greater than 50
np.sum(mask)

NameError: name 'mask' is not defined

In [13]:
# listing elemts that are greater than 50
new_array[mask]

NameError: name 'new_array' is not defined

**Operations in numpy array**

In [ ]:
a = np.arange(1,10)
b = np.arange(10,19)


In [ ]:
a

In [ ]:
b

In [ ]:
# sum
sum_array = a + b
sum_array

In [ ]:
# difference 
sub_array = b - a
sub_array

In [ ]:
# multiply
mult_array = a * b
mult_array

In [ ]:
# square of a each elements 
sq_array = a**2
print(sq_array)

In [ ]:
# Now operation on (3*3) matrices
new_a = a.reshape(3,3)
new_b = b.reshape(3,3)

In [ ]:
new_a

In [ ]:
new_b

In [ ]:
# operation
sum_ = new_a + new_b
sum_


In [ ]:
subtract_ = new_b - new_a
subtract_

In [ ]:
multiply_ = new_a * new_b
multiply_

In [ ]:
new_a

In [ ]:
new_b

In [ ]:
# masking in new_a matrix 
mask = new_a > 5
print(mask)

In [ ]:
np.sum(mask)

In [ ]:
np.log(new_a)

In [ ]:
np.sin(new_a)

**Matrix Dot Product**

In [ ]:
new_a

In [ ]:
new_b

In [ ]:
# How dot product works
'''
[ 1*10+2*13+3*16  1*11+2*14+3*17  1*12+2*15+3*18]
[ 4*10+5*13+6*16  4*11+5*14+6*17  4*12+5*15+6*18]
[ 7*10+8*13+9*16  7*11+8*14+9*17  7*12+8*15+9*18] 

columns of first matrix must match with rows of second matux to perform dot product.
result take number of rows from first matrix and columns from second matrix
'''

In [ ]:
product = np.dot(new_a, new_b)
print(product)

In [ ]:
new_a

In [ ]:
# square root of new_a matrix
np.sqrt(new_a)

In [ ]:
# sum
np.sum(new_a)

In [ ]:
# maximum
np.max(new_a)

In [ ]:
# minimum
np.min(new_a)

In [ ]:
# mean
np.mean(new_a)

In [ ]:
# standard deviation
np.std(new_a)

In [ ]:
# sum all by column wise
np.sum(new_a, axis=0)

In [ ]:
# sum all by rows wise
np.sum(new_a, axis=1)

In [ ]:
# Mean by column wise
np.mean(new_a, axis=0)

In [ ]:
# Mean by rows wise
np.mean(new_a, axis=1)

**Shape Manupulation**

In [ ]:
A = np.arange(0,24)
print(A)

In [ ]:
# reshaping 
array = A.reshape(6,4)
print(array)

In [ ]:
# flatten: converting array into 1 dimensional array. 
one_d_array = A.flatten()
print(one_d_array)

In [ ]:
# Transpose: Changing columns into rows and rows into columns
print(array)
print("\nTranspose of array:\n",array.T)

In [ ]:
# Random array
a = np.random.randint(0,11,(3,2))
b = np.random.randint(0,11,(3,2))
print(a)
print()
print(b)

In [ ]:
# Vstack: Putting a and b vertically
v_stack = np.vstack((a,b))
print(v_stack)

In [ ]:
# Hstack: putting a and b horizontally 
h_stack = np.hstack((a,b))
print(h_stack)

**Broadcasting**
- First Rule of Numpy: 2 Arrays can performs opertions only when they have same shapes
- broadcasting let two arrays of different shapes to do some operations.
    - A small array will repeat itself, and convert to the same shape as of another array.

In [ ]:
A = np.random.randint(0,10,size=(3,3))
B = np.array([[1,2,3]])
print(A)
print()
print(B)

In [ ]:
# A and B is not same type of matrix but through broadcasting we can calculate two matrix A and B. 
# Boardcasting make B into 3x3 matrix by copying elements ([1,2,3],[1,2,3],[1,2,3])
C = A + B
print(C)

In [ ]:
B.T

In [ ]:
A + B.T

In [ ]:
# A = [[5 7 0]
#     [1 0 9]
#     [0 0 0]]

new_C = A + 1
print(new_C)

**Vectorization**

In [ ]:
a = np.array([1,2])
b = np.array([5,5])
print("a vector:",a)
print("\nb vector:",b)

In [ ]:
# how to find distance between a and b vector : formula = (x1-y2)**2 + (x2-y2)**2 whole under square root
distance = np.sqrt(np.sum((b-a)**2))
print("Distance between a and b vector is:", distance)

In [ ]:
# Now 2 * 2 matrix/vector and note: you can do it up to n*n matrix/vector
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])
print("A:\n", A)
print("\nB:\n",B)

In [ ]:
distance = np.sqrt(np.sum(B-A)**2)
print("Distance between A and B vector is:", distance)